issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  disable:
    - gosimple
    - ineffassign
    - deadcode
    - unused
    - structcheck

run:
  skip-files:
    - ".+_test.go"
    - ".+_test_.+.go"
    - ".+.sql"
