version: "3.7"

networks:
  app-tier:
    driver: bridge

services:
  postgresql:
    container_name: iam-permission-postgresql
    image: "postgres:15.3"
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=iam_permission
      - POSTGRES_USER=iam_permission
      - POSTGRES_PASSWORD=123456
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - app-tier

  redis:
    container_name: iam-permission-redis
    image: "redis:latest"
    volumes:
      - ./volumes/redis:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - app-tier
